# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170320_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(max_length=200),
        ),
    ]
