# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20170320_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='user',
        ),
    ]
