# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20170320_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='temp@galvanize.com', max_length=100),
            preserve_default=False,
        ),
    ]
